spring:
  application:
    name: "dsm-practice"

  main:
    allow-bean-definition-overriding: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    open-in-view: false
    show-sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 128MB

  freemarker:
    cache: false
  thymeleaf:
    cache: false

  jwt:
    secretKey: ${SECRET_KEY}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}
    header: ${HEADER}
    prefix: ${PREFIX}

server:
  port: ${RUN_PORT}
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-exception: off
    include-message: never

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/api-swagger
    disable-swagger-default-url: true
